var x = 4;
var y = -x;
console.log('value of x is:',x);
console.log("value of y is:",y);
var z = !(x>10);
console.log(z);
var msg = "hi" + "ramya";
console.log(msg);
var result = x > 10 ? "true" : "false";
console.log(result);
console.log(typeof x);
var r = "ramya";
console.log(typeof r);
